baseURL = "/"
languageCode = "en-gb"
title = "Historic Environment Quicksearch"
theme = "govukhugo"
publishDir = "docs"
staticDir = ["static", "docs"]
canonifyurls = true

[markup.goldmark.renderer]
unsafe = true


[module]
  [[module.imports]]
    path = 'github.com/flaxandteal/govukhugo'
  [[module.imports]]
    path = 'github.com/flaxandteal/starches'
  [[module.imports]]
    path = 'github.com/flaxandteal/hugo-cookies'

[params]
govuk = false
logotext = "ABC"
product = "Public Asset Quickview"
phase = "alpha"
feedbackurl = "/feedback/"
archesurl = "http://localhost:8000/"
ga4token = "GTM-K3B6FBDS"
ga4gtag = "G-HJZQETB39E"
cookies = "cookies.md"

[[module.mounts]]
source = "content"
target = "content"

[[module.mounts]]
source = "static"
target = "static"

[[module.mounts]]
source = "docs/pagefind"
target = "static/pagefind"

[[module.mounts]]
source = "docs/definitions"
target = "static/definitions"
