name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - dev
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - dev

jobs:
  test_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Test Job
    steps:
      - uses: actions/checkout@v3
      
      - name: Log in to Docker Registry
        run: echo ${{ secrets.DOCKER_REGISTRY_TOKEN }} | docker login ghcr.io -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      
      - name: Pull Docker Image
        run: docker pull ghcr.io/flaxandteal/quartz-starches:latest
      
      - name: Extract docs Directory
        run: |
          mkdir -p docs
          docker create --name temp-container ghcr.io/flaxandteal/quartz-starches:latest
          docker cp temp-container:/usr/share/nginx/html/. ./docs
          docker rm temp-container
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run CSS linter
        run: npm run test:lint:css
      
      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          start: npx http-server docs -a 127.0.0.1 -p 1314 -c-1
          wait-on: 'http://127.0.0.1:1314'
          wait-on-timeout: 60
          browser: chrome
          config: baseUrl=http://127.0.0.1:1314
          install: false
      
      - name: Upload Cypress screenshots on failure
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore
      
      - name: Upload Cypress videos
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore

  deploy_job:
    name: Deploy
    needs: test_job
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker Registry
        run: echo ${{ secrets.DOCKER_REGISTRY_TOKEN }} | docker login ghcr.io -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      
      - name: Pull Docker Image
        run: docker pull ghcr.io/flaxandteal/quartz-starches:latest
      
      - name: Extract docs Directory
        run: |
          mkdir -p docs
          docker create --name temp-container ghcr.io/flaxandteal/quartz-starches:latest
          docker cp temp-container:/usr/share/nginx/html/. ./docs
          docker rm temp-container
      
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GREEN_BAY_084176900 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "docs"
          skip_app_build: true
