name: Run full build
run-name: Run full build
on:
  workflow_dispatch: {}
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-starches:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        visibility:
          - image: catalina-starches-public
            starches_include_private: '0'
          - image: catalina-starches
            starches_include_private: '1'
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: 'true'

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker build . \
            --file ./Dockerfile \
            --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/${{ matrix.visibility.image }}:latest \
            --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/${{ matrix.visibility.image }}:${{ github.sha }} \
            --build-arg STARCHES_INCLUDE_PRIVATE=${{ matrix.visibility.starches_include_private }}
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/${{ matrix.visibility.image }}:latest
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/${{ matrix.visibility.image }}:${{ github.sha }}
