name: Deploy to GHCR

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

on:
  workflow_run:
    workflows: ["Build and Test"]
    types:
      - completed
    branches:
      - dev

jobs:
  deploy_job:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Deploy
    runs-on: [new-zealand-starches]
    permissions:
      contents: read
      packages: write
    steps:
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Docker Image
        run: docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/catalina-starches-private:${{ github.event.workflow_run.head_sha }}

      - name: Push as latest
        run: |
          docker tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/catalina-starches-private:${{ github.event.workflow_run.head_sha }} ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/catalina-starches-private:latest
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/catalina-starches-private:latest
